config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to:'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/shared/_error_messages.html.erb
<%# 他のオブジェクトでも動作するように@userをobjectに変更 %>
<% if object.errors.any? %>

  <div id="error_explanation">
    <div class="alert alert-error">
        <%# 他のオブジェクトでも動作するように@userをobjectに変更 %>
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
       <%# 他のオブジェクトでも動作するように@userをobjectに変更 %>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%# ステータスフィードのパーシャル %>

<%# もし@feed_itemsに何か入っていたら %>
<% if @feed_items.any? %>

  <ol class="microposts">

    <%# フィードパーシャルを追加 %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
    <%# フィードアイテムとして:collectionパラメーターを渡しているので、renderはコレクションの各アイテムを表示するために与えられたパーシャル (この場合は’feed_item’)を使用してくれる。(以前の表示では、render ’shared/micropost’のように:partialパラメーターを省略していたが、:collectionパラメーターがある場合はこの記法では正常に動作しない。)   %>

  </ol>
  <%# paginationを実装 %>
  <%= will_paginate @feed_items %>

<% end %>

app/views/shared/_feed_item.html.erb
<%# 単一のフィードアイテム用のパーシャル %>

<%# 各フィードにCSS idを追加 %>
<li id="<%= feed_item.id %>">

  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content" ><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>

  <%# フィードアイテムパーシャルに削除リンクを追加 %>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%# マイクロポスト作成フォームのパーシャル %>

<%# fに@micropostの内容を代入 %>
<%= form_for(@micropost) do |f| %>

  <%# エラーメッセージを表示 %>
  <%= render 'shared/error_messages', object: f.object %>
                                                        <%# object:は値、f.objectは@micropostになる。つまり、object: f.objectはerror_messagesパーシャルの中でobjectという変数名を作成し、このobject変数を使用してカスタムエラーメッセージを作成できる %>
  <div class="field">

    <%# マイクロポスト作成フォーム %>
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>

  <%# submitボタン %>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<%# フォローしているユーザーとフォロワーの統計情報を表示するパーシャル %>

<%# 「||=」は左の変数が偽か未定義であれば右の内容を左に代入するという意味 。ユーザー表示ページとHomeページの両方に表示されるので、以下のコードを使用して適切な方を選択している。@userが nilでない場合 (つまりプロファイルページの場合) は何もせず、nilの場合 (つまりHomeページの場合) には@userにカレントユーザーを設定する %>
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">

    <strong id="following" class="stat">
    <%# CSS idを指定していることにもぜひ注目。こうしておくと、11.2.5でAjaxを実装するときに便利。そこでは、一意のidを指定してページ要素にアクセスしている %>

      <%# フォローしているユーザーの人数は以下の関連付けを使用して計算している %>
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">

      <%# フォロワーの人数は、以下の関連付けを使用して計算している %>
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%# ユーザー情報サイドバーのパーシャル %>

<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size:52 %>
</a>
<h1>
  <%# current_userを表示 %>
  <%= current_user.name %>
</h1>
<span>
  <%# 自分のプロフィールへのリンク %>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%# マイクロポストの件数をカウント %>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>